#!/bin/bash

run() {
  python run.py
}

schedule() {
  python scheduler.py
}

format() {
  ruff format .
  prettier --write "**/*.{json,md}"
}

setup() {
  pip install -r requirements.txt
  echo "Setup complete, configure your credentials in config/users/*.json"
}

deploy() {
  lift deploy
}
